package = prompt('package name: ')
version = prompt('package version: ', '0.1')
author = prompt('package author: ')
author_email = prompt('package author email: ')
description = prompt('description: ', '')
url = prompt('url: ')  
